<?php

return [
    'website_name' => 'Sniffr',
    'website_description' => 'Sniffr\'s Online Video Licensing Platform',
    'logo' => 'logo-sniffr-white.png',
    'favicon' => '',
    'system_email' => 'admin@admin.com',
    'demo_mode' => 0,
    'enable_https' => 0,
    'theme' => 'default',
    'facebook_page_id' => 'uniladmag',
    'google_page_id' => NULL,
    'twitter_page_id' => 'unilad',
    'youtube_page_id' => 'uniladtv',
    'google_tracking_id' => 'UA-45819798-4',
    'google_oauth_key' => NULL,
    'created_at' => '0000-00-00 00:00:00',
    'updated_at' => '2018-02-01 16:33:14',
    'videos_per_page' => 12,
    'posts_per_page' => 12,
    'free_registration' => 0,
    'activation_email' => 0,
    'premium_upgrade' => 1,
];
