<template>
    <div class="terms-section">
        <section id="header" class="page-videos">
            <div class="header-content">
                <div class="position-center">
                    <h1 class="heading">Terms &amp; Conditions</h1>
                </div>
            </div>
        </section>

        <!-- Terms & conditions -->
        <section class="videos-section section-space">
            <v-container grid-list-lg>
                <div>
                    <h2 class="text-center text-uppercase">Terms Of Use</h2>
                    <p>SNIFFRMEDIA.CO.UK SERVICE USER AGREEMENT</p>
                    <p>Acceptance of User Agreement.</p>
                    <p>1. By registering for and/or using the Services in any manner, including but not limited to visiting or browsing the Site, you agree to this User Agreement and all other operating rules, policies and procedures that may be published from time to time on the Site by us, each of which is incorporated by reference and each of which may be updated from time to time without notice to you.</p>
                    <p>2. Certain of the Services may be subject to additional terms and conditions specified by us from time to time; your use of such Services is subject to those additional terms and conditions, which are incorporated into this User Agreement by this reference.</p>
                    <p>3. This User Agreement applies to all users of the Services, including, without limitation, users who are contributors of content, information, and other materials or services, registered or otherwise.</p>
                    <p>4. ARBITRATION NOTICE AND CLASS ACTION WAIVER: EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
                    <p>Eligibility.</p>
                    <p>You represent and warrant that you are at least 18 years of age. If you are under age 18, you may not, under any circumstances or for any reason, use the Services. We may, in our sole discretion, refuse to offer the Services to any person or entity and change its eligibility criteria at any time. You are solely responsible for ensuring that this User Agreement is in compliance with all laws, rules and regulations applicable to you and the right to access the Services is revoked where this User Agreement or use of the Services is prohibited or to the extent offering, sale or provision of the Services conflicts with any applicable law, rule or regulation. Further, the Services are offered only for your use, and not for the use or benefit of any third party.</p>
                    <p>Content.</p>
                    <p>Definition.</p>
                    <p>For purposes of this User Agreement, the term “Content” includes, without limitation, information, data, text, photographs, videos, audio clips, written posts, articles, comments, software, scripts, graphics, and interactive features generated, provided, or otherwise made accessible on or through the Services. For the purposes of this Agreement, “Content” also includes all User Content (as defined below).</p>
                    <p>User Content.</p>
                    <p>All Content added, created, uploaded, submitted, distributed, or posted to the Services by users (collectively “User Content”), whether publicly posted or privately transmitted, is the sole responsibility of the person who originated such User Content. You represent that all User Content provided by you is accurate, complete, up-to-date, and in compliance with all applicable laws, rules and regulations. You acknowledge that all Content, including User Content, accessed by you using the Services is at your own risk and you will be solely responsible for any damage or loss to you or any other party resulting therefrom. We do not guarantee that any Content you access on or through the Services is or will continue to be accurate.</p>
                    <p>Notices and Restrictions.</p>
                    <p>The Services may contain Content specifically provided by us, our partners or our users and such Content is protected by copyrights, trademarks, service marks, patents, trade secrets or other proprietary rights and laws. You shall abide by and maintain all copyright notices, information, and restrictions contained in any Content accessed through the Services.</p>
                    <p>Availability of Content.</p>
                    <p>We do not guarantee that any Content will be made available on the Site or through the Services. We reserve the right to, but do not have any obligation to, (i) remove, edit, modify or otherwise manipulate any Content in our sole discretion, at any time, without notice to you and for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content or if we are concerned that you may have violated this User Agreement), or for no reason at all and (ii) to remove or block any Content from the Services.</p>
                    <p>Rules of Conduct.</p>
                    <p>As a condition of use, you promise not to use the Services for any purpose that is prohibited by these Terms of Use. You are responsible for all of your activity in connection with the Services.
                        <br> You shall not (and shall not permit any third party to) either (a) take any action or (b) upload, download, post, submit or otherwise distribute or facilitate distribution of any Content on or through the Service, including without limitation any User Content, that:</p>
                    <p>1. infringes any patent, trademark, trade secret, copyright, right of publicity or other right of any other person or entity or violates any law or contractual duty;</p>
                    <p>2. you know is false, misleading, untruthful or inaccurate;</p>
                    <p>3. is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another’s privacy, tortious, obscene, vulgar, pornographic, offensive, profane, contains or depicts nudity, contains or depicts sexual activity, or is otherwise inappropriate as determined by us in our sole discretion;</p>
                    <p>4. constitutes unauthorized or unsolicited advertising, junk or bulk e-mail (“spamming”);</p>
                    <p>5. contains software viruses or any other computer codes, files, or programs that are designed or intended to disrupt, damage, limit or interfere with the proper function of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any system, data, password or other information of ours or of any third party;</p>
                    <p>6. impersonates any person or entity, including any of our employees or representatives; or</p>
                    <p>7. includes anyone’s identification documents or sensitive financial information.</p>
                    <p>You shall not: (i) take any action that imposes or may impose (as determined by us in our sole discretion) an unreasonable or disproportionately large load on our (or our third party providers’) infrastructure; (ii) interfere or attempt to interfere with the proper working of the Services or any activities conducted on the Services; (iii) bypass, circumvent or attempt to bypass or circumvent any measures we may use to prevent or restrict access to the Services (or other accounts, computer systems or networks connected to the Services); (iv) run any form of auto-responder or “spam” on the Services; (v) use manual or automated software, devices, or other processes to “crawl” or “spider” any page of the Site; (vi) harvest or scrape any Content from the Services; or (vii) otherwise take any action in violation of our guidelines and policies.</p>
                    <p>You shall not (directly or indirectly): (i) decipher, decompile, disassemble, reverse engineer or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Services (including without limitation any application), except to the limited extent applicable laws specifically prohibit such restriction, (ii) modify, translate, or otherwise create derivative works of any part of the Services, or (iii) copy, rent, lease, distribute, or otherwise transfer any of the rights that you receive hereunder. You shall abide by all applicable local, state, national and international laws and regulations.</p>
                    <p>We also reserve the right to access, read, preserve, and disclose any information as we reasonably believe is necessary to (i) satisfy any applicable law, regulation, legal process or governmental request, (ii) enforce this User Agreement, including investigation of potential violations hereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect the rights, property or safety of us, our users and the public.</p>
                    <p>Third Party Services.</p>
                    <p>The Services may permit you to link to other websites, services or resources on the Internet, including but not limited to our sponsors and Facebook, and other websites, services or resources may contain links to the Services. When you access third party resources on the Internet, you do so at your own risk. These other resources are not under our control, and you acknowledge that we are not responsible or liable for the content, functions, accuracy, legality, appropriateness or any other aspect of such websites or resources. The inclusion of any such link does not imply our endorsement or any association between us and their operators. You further acknowledge and agree that we shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such website or resource.</p>
                    <p>Termination.</p>
                    <p>We may terminate your access to all or any part of the Services at any time, with or without cause, with or without notice, effective immediately, which may result in the forfeiture and destruction of all information associated with your membership. If you wish to terminate your Account, you may do so by following the instructions on the Site or through the Services. All provisions of this User Agreement which by their nature should survive termination shall survive termination, including, without limitation, licenses of User Content, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
                    <p>Warranty Disclaimer.</p>
                    <p>We have no special relationship with or fiduciary duty to you. You acknowledge that We have no duty to take any action regarding:</p>
                    <p>1. which users gain access to the Services;</p>
                    <p>2. what Content you access via the Services; or</p>
                    <p>3. how you may interpret or use the Content.</p>
                    <p>You release us from all liability for you having acquired or not acquired Content through the Services. We make no representations concerning any Content contained in or accessed through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, or legality of material or Content contained in or accessed through the Services.</p>
                    <p>THE SERVICES AND CONTENT ARE PROVIDED “AS IS”, “AS AVAILABLE” AND WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. WE, AND OUR DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, PARTNERS AND CONTENT PROVIDERS DO NOT WARRANT THAT: (I) THE SERVICES WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (II) ANY DEFECTS OR ERRORS WILL BE CORRECTED; (III) ANY CONTENT OR SOFTWARE AVAILABLE AT OR THROUGH THE SERVICES IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (IV) THE RESULTS OF USING THE SERVICES WILL MEET YOUR REQUIREMENTS. YOUR USE OF THE SERVICES IS SOLELY AT YOUR OWN RISK.</p>
                    <p>Indemnification.</p>
                    <p>You shall defend, indemnify, and hold harmless us, our affiliates and each of our and their respective employees, contractors, directors, suppliers and representatives from all liabilities, claims, and expenses, including reasonable attorneys’ fees, that arise from or relate to your use or misuse of, or access to, the Services, Content, or otherwise from your User Content, violation of this User Agreement, or infringement by you, or any third party using your Account or identity in the Services, of any intellectual property or other right of any person or entity. We reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will assist and cooperate with us in asserting any available defenses.</p>
                    <p>Governing Law and Jurisdiction.</p>
                    <p>This User Agreement shall be governed by and construed in accordance with the laws of the United Kingdom You agree that any dispute arising from or relating to the subject matter of this User Agreement shall be governed by the exclusive jurisdiction of the courts of the United Kingdom.</p>
                    <p>Modification.</p>
                    <p>We reserve the right, in our sole discretion, to modify or replace any part of this User Agreement, or change, suspend, or discontinue the Services (including without limitation, the availability of any feature, database, or content) at any time by posting a notice on the Site or by sending you notice through the Services, via e-mail or by another appropriate means of electronic communication. We may also impose limits on certain features and services or restrict your access to parts or all of the Services without notice or liability. While we will timely provide notice of modifications, it is also your responsibility to check this User Agreement periodically for changes. Your continued use of the Services following notification of any changes to this User Agreement constitutes acceptance of those changes.</p>
                    <p>Miscellaneous.</p>
                    <p>Entire Agreement and Severability.</p>
                    <p>This User Agreement is the entire agreement between you and us with respect to the Services, including use of the Site, and supersede all prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and us with respect to the Services. If any provision of this User Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this User Agreement will otherwise remain in full force and effect and enforceable. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder</p>
                    <p>Force Majeure.</p>
                    <p>We shall not be liable for any failure to perform our obligations hereunder where such failure results from any cause beyond our reasonable control, including, without limitation, mechanical, electronic or communications failure or degradation.</p>
                    <p>Assignment.</p>
                    <p>This User Agreement is personal to you, and is not assignable, transferable or sublicensable by you except with our prior written consent. We may assign, transfer or delegate any of our rights and obligations hereunder without consent.</p>
                    <p>Agency.</p>
                    <p>No agency, partnership, joint venture, or employment relationship is created as a result of this User Agreement and neither party has any authority of any kind to bind the other in any respect.</p>
                    <p>Notices.</p>
                    <p>Unless otherwise specified in this User Agreement, all notices under this User Agreement will be in writing and will be deemed to have been duly given when received, if personally delivered or sent by certified or registered mail, return receipt requested; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; or the day after it is sent, if sent for next day delivery by recognized overnight delivery service. Electronic notices should be sent to enquiries@SNIFFRMEDIA.co.uk.</p>
                    <p>No Waiver.</p>
                    <p>Our failure to enforce any part of this User Agreement shall not constitute a waiver of our right to later enforce that or any other part of this User Agreement. Waiver of compliance in any particular instance does not mean that we will waive compliance in the future. In order for any waiver of compliance with this User Agreement to be binding, we must provide you with written notice of such waiver through one of our authorized representatives.</p>
                    <p>Headings.</p>
                    <p>The section and paragraph headings in this User Agreement are for convenience only and shall not affect their interpretation.</p>
                    <p>These terms may be superseded by agreement or whether or terms are presented and accepted.</p>
                    <p>Effective Date of User Agreement: 15-9-2013</p>
                </div>
            </v-container>
        </section>

    </div>
</template>
<script>

</script>